apiVersion: apps/v1
kind: Deployment
metadata:
  name: flows
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flows
  template:
    metadata:
      labels:
        app: flows
    spec:
      containers:
      - name: flows
        image: "{{ .Values.Config.Image.Repository }}/flows:obslab-v1"
        imagePullPolicy: Always
        ports:
        - containerPort: 3400
        env:
        - name: POSTGRES_HOST
          value: "db-service.movieguru.svc.cluster.local"
        - name: PROJECT_ID
          value: {{ .Values.Config.projectID }}
        - name: POSTGRES_DB_USER_PASSWORD
          value: "minimal"
        - name: POSTGRES_DB_USER
          value: "minimal-user"
        - name: POSTGRES_DB_NAME
          value: "fake-movies-db"
        - name: TABLE_NAME
          value: "movies"
        - name: LOCATION
          value: {{ .Values.Config.geminiApiLocation }}
---
apiVersion: v1
kind: Service
metadata:
  name: flows-service
  namespace: movieguru
spec:
  selector:
    app: flows 
  ports:
  - protocol: TCP
    port: 3400
    targetPort: 3400
  type: ClusterIP