services:
  agent:
    build:
      context: agents 
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/.key.json
      DB_PATH: "/app/data_london/"
      GOOGLE_CLOUD_PROJECT: $PROJECT_ID
      GOOGLE_CLOUD_LOCATION: $LOCATION
      GOOGLE_GENAI_USE_VERTEXAI: "TRUE"
      PRINT_HEALTH_STATUS: "False"
      OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT: "true"
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
    volumes:
      - .key.json:/app/.key.json:ro
      - ./data_london/london_travel.sql:/app/data_london/london_travel.sql

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API_BASE_URL=http://localhost:8001
    depends_on:
      - agent