services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: main
    volumes:
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      # Optional: Pre-fill the server host for Adminer.
      # 'db' is the service name of the PostgreSQL container within the Docker network.
      ADMINER_DEFAULT_SERVER: db
  agent:
    build:
      context: code
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/.key.json
      PG_HOST: db
      GOOGLE_CLOUD_PROJECT: "o11y-movie-guru"
      GOOGLE_GENAI_USE_VERTEXAI: "TRUE"
      GOOGLE_CLOUD_LOCATION: "us-central1"
      PRINT_HEALTH_STATUS: "False"
    volumes:
      - .key.json:/app/.key.json:ro