apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: ltc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: "{{ .Values.Config.Image.Repository }}/agent:{{ .Values.Config.Image.Tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PG_HOST
          value: "db-service.ltc.svc.cluster.local"
        - name: GOOGLE_CLOUD_PROJECT
          value: {{ .Values.Config.projectID }}
        - name: GOOGLE_CLOUD_LOCATION
          value: {{ .Values.Config.geminiApiLocation }}
        - name:  GOOGLE_GENAI_USE_VERTEXAI
          value: "TRUE"
        - name: PRINT_HEALTH_STATUS
          value: "{{ .Values.Config.printHealthStatus }}"
        - name: PORT
          value: "8000"
        - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: ltc
spec:
  selector:
    app: agent 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: {{ .Values.Config.AgentIP }}


