Config: 
  Image:
    Repository: us-central1-docker.pkg.dev/o11y-movie-guru/london-travel-agency
    Tag: obslab-v1
    
  geminiApiLocation: us-central1
  useVertexAI: "TRUE"
  printHealthStatus: "False"
